src/Web/WebMVC/Models/Cart/CartDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models.Cart
{
    public class CartDetails
    {
        public decimal Total { get; set; }
        public virtual List<CartItem> Items { get; set; }
    }
}

src/Web/WebMVC/Models/Cart/CartItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models.Cart
{
    public class CartItem
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    }
}

src/Web/WebMVC/Models/Cart/DTO/CartItemDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models.Cart
{
    public class CartItemDTO
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
    }
}

src/Web/WebMVC/Models/Cart/DTO/UpdateCartItemDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMVC.Models.Cart.DTO
{
    public class UpdateCartItemDTO
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
    }
}

src/Web/WebMVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using WebMVC.Infastrucutre.Helper;
using WebMVC.Infrastructure;
using WebMVC.Models;
using WebMVC.Models.Cart;
using WebMVC.Models.Cart.DTO;
using WebMVC.Services.Intrefaces;

namespace WebMVC.Controllers
{
    [Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]
    public class CartController : MyController
    {
        private ICartService _cartService;
        private ICatalogService _catalogService;
        private IIdentityParser<ApplicationUser> _identityParser;

        public CartController(
            ICartService cartService, 
            ICatalogService catalogService,
            ITenantManagerService tenantManagerService,
            IIdentityParser<ApplicationUser> identityParser,
            ILogger<MyController> logger) 
            : base(tenantManagerService, identityParser, logger)
        {
            _cartService = cartService;
            _catalogService = catalogService;
            _identityParser = identityParser;
        }

        public async Task<IActionResult> Index()
        {
            await ServiceReporting.Log($"Get cart");
            // get the user id 
            var user = _identityParser.Parse(HttpContext.User);
            // get the cart of user
            var cartDetails = await _cartService.GetCart(user);
            await ServiceReporting.Log("Display cart");
            // load view
            return View(cartDetails);
        }

        public async Task<IActionResult> AddItemToCart(int id, int qty)
        {
            await ServiceReporting.Log($"Add item to cart");
            // TODO: ApiGateway Agregation
            // STEP 1: Get item
            var item = await _catalogService.GetSingleCatalogItemById(id);
            if(item?.Id != null)
            {
                // get the user id 
                var user = _identityParser.Parse(HttpContext.User);
                var newCartItem = new CartItemDTO
                {
                    ItemId = item.Id,
                    Description = item.Description,
                    Name = item.Name,
                    Price = item.Price,
                    Quantity = qty
                };
                // STEP 2: Add item to cart
                await _cartService.AddItemToCart(user, newCartItem);
            }

            return RedirectToAction("Index", "Cart");
        }

        public async Task<IActionResult> UpdateCart(UpdateCartItemDTO[] items)
        {
            await ServiceReporting.Log($"Update cart");
            if(items.Length == 0)
            {
                return RedirectToAction("Index", "Cart");
            }
            // get the user id 
            var user = _identityParser.Parse(HttpContext.User);
            var cartDetails = await _cartService.GetCart(user);

            foreach (UpdateCartItemDTO itm in items)
            {
                var cartItem = cartDetails.Items.FirstOrDefault(i => i.Id == itm.Id);
                cartItem.Quantity = itm.Quantity;
            }

            await _cartService.UpdateCart(user, cartDetails);

            return RedirectToAction("Index", "Cart");
        }
    }
}

src/Web/WebMVC/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMVC.Infastrucutre.Helper;
using WebMVC.Infrastructure;
using WebMVC.Models;
using WebMVC.Services;
using WebMVC.Services.Intrefaces;
using WebMVC.ViewModels.Catalog;

namespace WebMVC.Controllers
{
    [Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]
    public class CatalogController : MyController
    {
        private ICatalogService _catalogService;

        public CatalogController(
            ICatalogService catalogService, 
            ITenantManagerService tenantManagerService, 
            IIdentityParser<ApplicationUser> identityParser, 
            ILogger<MyController> logger)
            : base(tenantManagerService, identityParser, logger)
        {
            _catalogService = catalogService; 
        }

        public async Task<IActionResult> Index()
        {
            await ServiceReporting.Log($"Get catalog");
            // Get Catalog items from CatalogService
            var items = await _catalogService.GetCatalogItems();
            // Create view model
            var data = new IndexViewModel()
            {
                CatalogItems = items
            };
            await ServiceReporting.Log("Display catalog");
            // load view
            return View(data);
        }
    }
}

src/Web/WebMVC/Views/Cart/Index.cshtml
@model WebMVC.Models.Cart.CartDetails
@{
    ViewData["Title"] = "Cart  Page";
}


<div class="container">
    @if (Model != null)
    {
        <form action="/Cart/UpdateCart" method="post">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Qty</th>
                        <th scope="col">Name</th>
                        <th scope="col">Unit Price</th>
                        <th scope="col">Price</th>
                    </tr>
                </thead>
                <tbody>
                    @{int i = 0;}
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <th scope="row">
                                <input type="hidden" value="@item.Id" name="items[@i].Id" />
                                <input type="number" name="items[@i].Quantity" min="1" value="@item.Quantity">
                            </th>
                            <td>@item.Name</td>
                            <td>R @Math.Round(item.Price, 2)</td>
                            <td>R @Math.Round(item.Price * item.Quantity, 2)</td>
                        </tr>
                        i++;
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th>R @Math.Round(Model.Total, 2)</th>
                    </tr>
                </tfoot>
            </table>
            <button type="submit" class="btn btn-primary float-right ml-3 mr-3">Update Cart</button>
        </form>
        <div>
            <form asp-action="CreateOrder" asp-controller="Order">
                <button type="submit" class="btn btn-primary float-right">Complete Order</button>
            </form>
        </div>
    }
    else
    {
        <div class="text-center">
            <div class="alert alert-info" role="alert">
                You have no items in your Cart!
                <br />
                <a class="btn btn-primary" role="button" asp-area="" asp-controller="Catalog" asp-action="Index">Go To Catalog</a>
            </div>
        </div>
    }
</div>